### ISSUE TITLE
Unknown SSL protocol error in connection

### ISSUE THREAD

**Issue by myurtsev** [msyk/FMDataAPI#1]
Hi, I have the following error when I try `$result = $fmdb->layoutname->query();` :

ErrorNumber: 35

Unknown SSL protocol error in connection to xx.xx.com:443

Any ideas?

**Comment by myurtsev** [comment]
I think I found the answer. My TLS version was 1.0 and version 1.2 is required to connect.

**Comment by msyk** [comment]
Yes, you are right.
