### ISSUE TITLE
HTTP 400 Bad Request

### ISSUE THREAD

**Issue by davidsilverthornsoftware** [msyk/FMDataAPI#19]
I have the sample script working fine with the test database, but I'm having trouble connecting with my own database, as I receive HTTP 400 Bad Request across the board. The requests work in Postman, however. Does the wrapper have difficulty handling database files that have spaces in it's filename?

**Comment by msyk** [comment]
Could you check the WPE log in FileMaker Server. You have to set to log both error and information. The log entry which you got the error could be informative.

**Comment by davidsilverthornsoftware** [comment]
The WPE log is rather sparse, but matsuo's commit resolved the problem. Thank you!

**Comment by msyk** [comment]
Thanks, Matsuo-san.
