### ISSUE TITLE
Fatal error object of class could not be converted to string

### ISSUE THREAD

**Issue by base64bits** [msyk/FMDataAPI#31]
When executing any API call at the end of the debugging result I keep getting this error: 

Recoverable fatal error: Object of class INTERMediator\FileMakerServer\RESTAPI\Supporting\FileMakerRelation could not be converted to string in /FMDataAPI.php on line 1446

Should I leave it and not worry about it?

I tried to fix it but it is beyond my skills at the moment.

I am using php 7.2.127.2.12

**Comment by matsuo** [comment]
It might be better to see samples/FMDataAPI_Sample.php.
https://github.com/msyk/FMDataAPI/blob/master/samples/FMDataAPI_Sample.php

In FMDataAPI_Sample.php:
```
$result = $fmdb->person_layout->query(/*array(array("id" => ">1"))*/);
// :
if (!is_null($result)) {
    foreach ($result as $record) {
        echo "id: {$record->id},";
        // :
    }
}
```

The following code causes "Recoverable fatal error: Object of class INTERMediator\FileMakerServer\RESTAPI\Supporting\FileMakerRelation could not be converted to string".

```
$result = $fmdb->person_layout->query();
echo $result;
```
