### ISSUE TITLE
Token per call rather than per action

### ISSUE THREAD

**Issue by base64bits** [msyk/FMDataAPI#34]
Looking at the FileMaker API logs I see that when I use the php script to perform a series of things the script creates a new token per each action, it will be nice to use only one token for all the actions and delete that token/sesion once the script is finished, let me know your thoughts.

Thanks!

**Comment by mbcbus** [comment]
@base64bits - are you using:
`new FMDataAPI("TestDB", "web", "password");`
Inside of a loop? If so you only need to use it once on your script.

If you have a number of scripts that need to share a token, then you can store the generated token from the above using the getSessionToken and setSessionToken functions. You'll need to keep your own timer as tokens expire (by default) after 15 minutes from the last call. 

Anytime you create a new class instance from the above, it will create a new connection to FileMaker. But you can reuse the same connection numerous times.

**Comment by msyk** [comment]
Sorry for a late response. Could you check the startCommunication() and endCommunication() methods for batch-like operations.

http://inter-mediator.info/FMDataAPI/classes/INTERMediator.FileMakerServer.RESTAPI.FMDataAPI.html#method_startCommunication
