### ISSUE TITLE
ErrorException (E_ERROR) Trying to get property 'portalDataInfo' of non-object

### ISSUE THREAD

**Issue by myurtsev** [msyk/FMDataAPI#36]
I get the following error when I try to fetch the data in a portal (with the FM18 release):

ErrorException (E_ERROR)
Trying to get property 'portalDataInfo' of non-object

I tried it like this:  $record->nameoftheportal
This worked with the FM17 version. The portal and the data exists in $record.

Any idea?

**Comment by msyk** [comment]
@myurtsev, thanks for reporting.

So, why don't you use the getPortalNames() and setPortalName() methods? As far as my code shows, the portalName property is private.

**Comment by myurtsev** [comment]
I mean the data in "portalData". 

<img width="357" alt="Schermafbeelding 2019-07-03 om 09 55 19" src="https://user-images.githubusercontent.com/10652725/60574027-0ad75a80-9d79-11e9-8948-0a73ea51ef3f.png">

**Comment by msyk** [comment]
Sorry, I can't get the reason so far. The error message 'Trying to get property 'portalDataInfo' of non-object' means to access the portalDataInfo property, but the all portalDataInfo property access are doing after checking to exist the portalDataInfo property.

If you don't mind, could you show me your code and FMDB?

**Comment by myurtsev** [comment]
`$show = $fmdb->web_shows->query( array(array('slug' => $slug, "showOnWeb"=>1)) );`

When I dump $show, it shows all the data including the portal data. Then when I try to get the portal data:

`$show->programmas_PROGRAMMA_FOTOS`

It throws the error mentioned above.

**Comment by msyk** [comment]
@myurtsev Sorry for late. Could you check to contain the 'portalDataInfo' property in the 'data' property of $show variable?
