### ISSUE TITLE
Multiple script parameters

### ISSUE THREAD

**Issue by myurtsev** [msyk/FMDataAPI#43]
Is it possible to send multiple script parameters in "script.param", as in a array?

**Comment by msyk** [comment]
The "script.param" requires just a string. Could you refer to the "script" parameter of below? I wrote an example for set multiple values on "script.param."
https://inter-mediator.info/FMDataAPI/classes/INTERMediator.FileMakerServer.RESTAPI.Supporting.FileMakerLayout.html#method_query
