### ISSUE TITLE
FileMaker Server 18.0.4

### ISSUE THREAD

**Issue by TheReiner** [msyk/FMDataAPI#45]
Hi,

Hi have 2 servers on version FMS 18 and i upgrade on 18.0.4 yesterday... Since, the FMDataAPI doesn't Work :-( 

Uncaught Exception: 2020-07-23 18:58:13 cURL in PHP / Error Code: 7, Error Message: Failed connect to X.X.X.X:443; Connection refused. [URL(POST): https://X.X.X.X:443/fmi/data/vLatest/databases/experts/sessions] in /var/www/vhosts/mydomain.com/httpdocs/FMDataAPI.php:2052
Stack trace:
#0 /var/www/vhosts/mydomain.com/httpdocs/FMDataAPI.php(1920): INTERMediator\FileMakerServer\RESTAPI\Supporting\CommunicationProvider-&gt;callRestAPI(Array, false, 'POST', Array, Array)
#1 /var/www/vhosts/mydomain.com/httpdocs/FMDataAPI.php(623): INTERMediator\FileMakerServer\RESTAPI\Supporting\CommunicationProvider-&gt;login()
#2 /var/www/vhosts/mydomain.com/httpdocs/do_login.php(31): INTERMediator\FileMakerServer\RESTAPI\Supporting\FileMakerLayout-&gt;create(Array)
#3 {main}
  thrown in 
<b>/var/www/vhosts/mydomain.com/httpdocs/FMDataAPI.php</b>

**Comment by msyk** [comment]
Is the certificate for TLS valid?

**Comment by TheReiner** [comment]
Yes is valid...

i think is a problem system... 
After Upgrade one serveur on Catalina, it's work again... But the second server still not working after Upgrade on Catalina... So i can say today, is not FMDataAPI :)

**Comment by msyk** [comment]
I see. And good luck!
