### ISSUE TITLE
accessing related field

### ISSUE THREAD

**Issue by frankeg** [msyk/FMDataAPI#46]
Hi,
There are related fields on the layout
eg. event::start (not in a portal )
but 
foreach ($result as $key=> $record ) { 
    $record->field("start", "event"); // this produce error even if I have a portal

    // only way I found it to work was having a portal and accessing it like below
    foreach ($record->event as $item) {
         print $item->start;
    }
}

What am I missing on how to access a related field not in a portal

Thanks
Frank

**Comment by msyk** [comment]
I think "$record->field("start", "event")" is correct so far, but I afraid that FMS changes responses or anything. Could you tell me the version number of your FileMaker Server?

**Comment by frankeg** [comment]
FileMaker Server 19.0.1.103
