### ISSUE TITLE
toArray return type error

### ISSUE THREAD

**Issue by codemongerr** [msyk/FMDataAPI#62]
When using `toArray` method defined in `https://github.com/msyk/FMDataAPI/blob/master/src/Supporting/FileMakerRelation.php` getting return type error. 

This is possibly due to on line number 310, 315, 320 when encoding and decoding the object, `json_decode` function is missing second parameter `true`. Second parameter set to `true` assure that `json_decode` always return an array. 

<img width="395" alt="Screen Shot 2022-06-22 at 12 21 12 PM" src="https://user-images.githubusercontent.com/19807449/174917797-d1bbeb15-7ea3-4222-a8c2-0f19b8285730.png">

Thanks.

**Comment by msyk** [comment]
@codemongerr Thanks a lot! I'm going to correct them and push it!

**Comment by codemongerr** [comment]
@msyk - You are very welcome and thanks for resolving it quickly.
