### ISSUE TITLE
Error in getPortalNames() in FileMakerRelation

### ISSUE THREAD

**Issue by PGMMattias** [msyk/FMDataAPI#64]
Perhaps I'm using this the wrong way, but I called getPortalNames() after calling getFirstRecord(), and received an error. That is because getNumberedRecord() changes the structure of the internal $data property.

What I did (leaving out the setup code):

`
$records = $fmdb->$layout->query($conditions, null, 1, 1);

$record = $records->getFirstRecord();

$portalNames = $record->getPortalNames(); //error
`

The error message: `property_exists(): Argument #1 ($object_or_class) must be of type object|string, array given`
File: inter-mediator/fmdataapi/src/Supporting/FileMakerRelation.php
Line: 339

One way to address this would be to change lines 257-259 from this:

`$value = new FileMakerRelation(
                $this->data[$num], $dataInfo, ($this->result == "PORTAL") ? "PORTALRECORD" : "RECORD",
                $this->errorCode, $this->portalName, $this->restAPI);`

into this (by surrounding the first parameter value with []):

`$value = new FileMakerRelation(
                [$this->data[$num]], $dataInfo, ($this->result == "PORTAL") ? "PORTALRECORD" : "RECORD",
                $this->errorCode, $this->portalName, $this->restAPI);`

That way, the array structure of the returned FileMakerRelation object stays the same as before.

**Comment by msyk** [comment]
@PGMMattias Thanks for letting me know the issue of recently added methods. I have to check the consequence and will fix soon.

**Comment by msyk** [comment]
The FileMakerRelation class is designed for relation, and it means stores multiple records as an array. Otherwise, I implemented some methods assuming that single record. I have to organize them based on use cases. So please wait for fixing this issues.

**Comment by PGMMattias** [comment]
Thank you very much! I will try this out.
