### ISSUE TITLE
toArray() returns nothing for portal reords

### ISSUE THREAD

**Issue by PGMMattias** [msyk/FMDataAPI#66]
Hello,

When iterating over portal records, I discovered that calling the toArray() method on a portal record returns an empty array.

In FileMakerRelation.php line 316 etc, the switch statement has a case for 'OK', 'PORTAL', and 'RECORD'. However my portal record's result property is 'PORTALRECORD'. So there is no matching case and the default value is returned by this method.

Simple pseudo code:
//$record is a FileMakerRelation where the result is RECORD
foreach ($record->getPortalNames() as $portalName) {
        foreach ($record->$portalName as $portalRecord) {
                $portalRecordArray = $portalRecord->toArray();
                print_r($portalRecordArray);
        }
}

Expected a dump of the values in each portal record, got empty arrays.

Thank you for this nice library!

**Comment by msyk** [comment]
@PGMMattias Thanks for reporting. I'm going to check and modify soon.

**Comment by msyk** [comment]
@PGMMattias The bug of toArray() was fixed. And I released Ver.30. Thanks!
