### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by PGMMattias** [msyk/FMDataAPI#67]
Hi,

In the documentation for the function FileMakerLayout::query() ,the parameter $portal is described like this:

> The array of the portal's object names. The query result is going to contain portals specified in this parameter. If you want to include all portals, set it null or omit it. Simple case is array('portal1', portal2'), and just includes two portals named 'portal1' and 'portal2' in the query result. If you set the range of records to a portal, you have to build associated array as like: array('portal1' => array('offset'=>1,'range'=>5), 'portal2' => null). The record 1 to 5 of portal1 include the query result, and also all records in portal2 do.

I tried using _array('portal1' => array('offset'=>1,'range'=>5))_, but I got a "missing array key" error. Looking at the code, it seems to expect something like this: array('portal1' => _array('offset'=>1,'**limit**'=>5))_.

However, FileMaker server does not like the request with portal parameters anyway. I will test that some more. Error message from FileMaker Server:
Error Code: 960, Error Message: Unknown parameter(s): _limit.portal1,_offset.portal1.

**Comment by msyk** [comment]
@PGMMattias thanks again! I will modify the key, and both key works. Give me a little while.

**Comment by msyk** [comment]
OMG. As you mentioned in the title, it's just a documentation issue.

**Comment by msyk** [comment]
Documentation was updated. Thanks @PGMMattias.
